# Generated by Django 2.0.3 on 2018-08-13 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dinner_platter',
            name='size',
            field=models.CharField(default='Small', max_length=64),
            preserve_default=False,
        ),
    ]
