# Generated by Django 2.0.3 on 2018-08-16 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_dinner_platter_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='dinner_platter',
        ),
        migrations.RemoveField(
            model_name='order',
            name='pasta',
        ),
        migrations.RemoveField(
            model_name='order',
            name='pizza',
        ),
        migrations.RemoveField(
            model_name='order',
            name='salad',
        ),
        migrations.RemoveField(
            model_name='order',
            name='sub',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
    ]
