# Generated by Django 2.0.3 on 2018-08-16 07:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orders', '0003_auto_20180816_0746'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=64)),
                ('dinner_platter', models.ManyToManyField(blank=True, to='orders.Dinner_Platter')),
                ('pasta', models.ManyToManyField(blank=True, to='orders.Pasta')),
                ('pizza', models.ManyToManyField(blank=True, to='orders.Pizza')),
                ('salad', models.ManyToManyField(blank=True, to='orders.Salad')),
                ('sub', models.ManyToManyField(blank=True, to='orders.Sub')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
